struct BMP_pressure_range { 
string<64> id1; //@key
double Pressure_high;    //in kPa
double Pressure_low;    //in kPa
};//@top-level

struct BMP_pressure { 
string<64> id; //@key
double Temperature; //in C
double Pressure;    //in kPa
double Altitude;    //in meter
};
